#!/usr/bin/env python3
"""Generate entropy coding lookup tables for HQLC rANS codec.

Outputs: src/entropy_tables.c

The main frequency LUT is imported from the Python reference codec
(hqlc_ref.py). This script converts it to C arrays and generates the
fixed-point helper tables (alpha edges, K*BW, log2 LUT).
"""

import math
import os
import sys

import numpy as np

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_DIR, "python-ref"))
import hqlc_ref

RANS_M = hqlc_ref.RANS_M
RANS_MAX_SYM = hqlc_ref.RANS_MAX_SYM
N_BANDS = hqlc_ref.N_BANDS
_RANS_K = hqlc_ref._RANS_K
_RANS_LUT_NBINS = hqlc_ref._RANS_LUT_NBINS
_RANS_LUT_ALPHA_EDGES = hqlc_ref._RANS_LUT_ALPHA_EDGES
_RANS_LUT_FREQ = hqlc_ref._RANS_LUT_FREQ
BAND_WEIGHTS = hqlc_ref.BAND_WEIGHTS


def gen_alpha_edges_q16():
    return [int(round(v * 65536)) for v in _RANS_LUT_ALPHA_EDGES]


def gen_k_bw_q16():
    return [
        int(round(_RANS_K * float(BAND_WEIGHTS[b]) * 65536)) for b in range(N_BANDS)
    ]


def gen_log2_frac_q8():
    return [int(round(math.log2(1.0 + i / 128.0) * 256.0)) for i in range(128)]


def validate():
    for i, row in enumerate(_RANS_LUT_FREQ):
        s = sum(row)
        assert s == RANS_M, f"freq row {i} sums to {s}"
    print("  Validation passed")


def fmt_2d(name, ctype, table):
    nr, nc = len(table), len(table[0])
    w = max(len(str(max(abs(v) for v in row))) for row in table)
    lines = [f"const {ctype} {name}[{nr}][{nc}] = {{"]
    for i, row in enumerate(table):
        vals = ", ".join(f"{v:>{w}}" for v in row)
        lines.append(f"    {{{vals}}}{',' if i < nr - 1 else ''}")
    lines.append("};")
    return "\n".join(lines)


def fmt_1d(name, ctype, values, per_line=8):
    n = len(values)
    w = max(len(str(v)) for v in values)
    lines = [f"const {ctype} {name}[{n}] = {{"]
    for i in range(0, n, per_line):
        chunk = values[i : i + per_line]
        vals = ", ".join(f"{v:>{w}}" for v in chunk)
        lines.append(f"    {vals}{',' if i + per_line < n else ''}")
    lines.append("};")
    return "\n".join(lines)


def main():
    print("Generating entropy tables...")
    validate()

    freq = [[int(x) for x in row] for row in _RANS_LUT_FREQ]
    edges = gen_alpha_edges_q16()
    k_bw = gen_k_bw_q16()
    log2 = gen_log2_frac_q8()

    # Reciprocal table for division-free rANS
    rcp = []
    for row in freq:
        rcp.append([min((1 << 32) // max(f, 1), (1 << 32) - 1) for f in row])

    src = os.path.join(PROJECT_DIR, "src", "entropy_tables.c")
    with open(src, "w") as f:
        f.write(
            "/* Auto-generated by scripts/gen_entropy_tables.py -- DO NOT EDIT */\n"
        )
        f.write('#include "entropy_tables.h"\n\n')
        f.write(fmt_2d("rans_lut_freq", "uint16_t", freq) + "\n\n")
        f.write(fmt_2d("rans_lut_rcp", "uint32_t", rcp) + "\n\n")
        f.write(fmt_1d("rans_lut_alpha_edges_q16", "uint32_t", edges, 4) + "\n\n")
        f.write(fmt_1d("rans_k_bw_q16", "int32_t", k_bw, 5) + "\n\n")
        f.write(fmt_1d("log2_frac_q8", "uint8_t", log2, 16) + "\n")
    print(f"  Wrote {src}")
    print("Done.")


if __name__ == "__main__":
    main()
