#!/usr/bin/env python3
"""Generate coefficient and exponent lookup tables for HQLC rANS coding.

Outputs: src/entropy_tables.c

Reads the frequency tables from the Python reference codec and generates
all derived C tables (reciprocals, cost, log2 LUT, sigma Q8).
"""

import math
import os
import sys

import numpy as np

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(PROJECT_DIR, "misc"))
from python.entropy import (
    _RANS_FREQ,
    _RANS_PAIR_SIGMA,
    RANS_M,
    RANS_MAX_SYM,
)

RANS_COEF_NTABLES = len(_RANS_FREQ)
RANS_COEF_NPAIRS = len(_RANS_PAIR_SIGMA)

EXP_NSLOTS = 13
# Dataset keys retained for compatibility with the trained table data.
EXP_MODEL_KEYS = ["d0", "dd0", "dd1"]
EXP_GROUPS = [
    [0],
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18, 19],
]
DEFAULT_EXP_DATA = os.path.join(PROJECT_DIR, "scripts", "exp_tables_data.npz")


def gen_log2_frac_q8():
    return [int(round(math.log2(1.0 + i / 128.0) * 256.0)) for i in range(128)]


def gen_rcp(freq):
    """floor((2^32 - 1) / f), clamped to 0xFFFFFFFF for f <= 1."""
    rcp = []
    for row in freq:
        rcp.append([min(0xFFFFFFFF // max(f, 1), 0xFFFFFFFF) for f in row])
    return rcp


def gen_cf(freq):
    """Cumulative frequencies: cf[s] = sum(freq[:s]), cf[MAX_SYM] = RANS_M."""
    out = []
    for row in freq:
        cf = [0]
        for f in row:
            cf.append(cf[-1] + f)
        out.append(cf)
    return out


def gen_cost_q8(freq, log2_frac):
    """Compute rANS symbol cost in Q8 fractional bits from frequency.

    Matches the C rans_freq_cost_q8() implementation exactly.
    """
    RANS_M_BITS = int(math.log2(RANS_M))
    MAX_COST = RANS_M_BITS * 256

    def freq_cost(f):
        if f == 0:
            return MAX_COST
        n = f.bit_length() - 1
        idx = (f >> (n - 7)) & 0x7F if n >= 7 else (f << (7 - n)) & 0x7F
        return MAX_COST - (n * 256 + log2_frac[idx])

    return [[freq_cost(f) for f in row] for row in freq]


def gen_sigma_q8(pair_sigma):
    """log2(sigma) in Q8 for alpha bin computation."""
    return [int(round(math.log2(s) * 256.0)) for s in pair_sigma]


def validate(freq):
    for i, row in enumerate(freq):
        s = sum(int(f) for f in row)
        assert s == RANS_M, f"freq row {i} sums to {s}, expected {RANS_M}"
    print(f"  Validated {len(freq)} frequency tables (sum={RANS_M})")


def gen_exponent_tables(path):
    source = np.load(path)
    group = np.zeros(20, dtype=int)
    for group_index, positions in enumerate(EXP_GROUPS):
        for band in positions:
            group[band] = group_index

    centers, cumulative, reciprocals, costs = [], [], [], []
    for model_key in EXP_MODEL_KEYS:
        for group_index in range(len(EXP_GROUPS)):
            freq = source[f"{model_key}_{group_index}_f"].astype(int)
            assert len(freq) == EXP_NSLOTS and freq.sum() == RANS_M
            centers.append(int(source[f"{model_key}_{group_index}_lo"]))

            cf = [0]
            for value in freq:
                cf.append(cf[-1] + int(value))
            cumulative.append(cf)
            reciprocals.append(
                [min(0xFFFFFFFF // max(int(value), 1), 0xFFFFFFFF) for value in freq]
            )
            costs.append(
                [int(round(-math.log2(value / RANS_M) * 256)) for value in freq]
            )

    return group.tolist(), centers, cumulative, reciprocals, costs


def fmt_2d(name, ctype, table, per_row=None):
    nr, nc = len(table), len(table[0])
    w = max(len(str(v)) for row in table for v in row)
    lines = [f"const {ctype} {name}[{nr}][{nc}] = {{"]
    for row in table:
        vals = ", ".join(f"{v:>{w}}" for v in row)
        lines.append(f"    {{{vals}}},")
    lines.append("};")
    return "\n".join(lines)


def fmt_1d(name, ctype, values, per_line=8):
    n = len(values)
    w = max(len(str(v)) for v in values)
    lines = [f"const {ctype} {name}[{n}] = {{"]
    for i in range(0, n, per_line):
        chunk = values[i : i + per_line]
        vals = ", ".join(f"{v:>{w}}" for v in chunk)
        lines.append(f"    {vals},")
    lines.append("};")
    return "\n".join(lines)


def main():
    print("Generating entropy tables...")

    exp_data = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_EXP_DATA

    freq = [[int(x) for x in row] for row in _RANS_FREQ]
    validate(freq)

    log2_frac = gen_log2_frac_q8()
    rcp = gen_rcp(freq)
    cf = gen_cf(freq)
    cost_q8 = gen_cost_q8(freq, log2_frac)
    sigma_q8 = gen_sigma_q8(_RANS_PAIR_SIGMA)
    exp_group, exp_center, exp_cf, exp_rcp, exp_cost_q8 = gen_exponent_tables(exp_data)

    src = os.path.join(PROJECT_DIR, "src", "entropy_tables.c")
    with open(src, "w") as f:
        f.write("/* Auto-generated by scripts/gen_entropy_tables.py - DO NOT EDIT */\n")
        f.write('#include "entropy_tables.h"\n\n')

        f.write("// Coefficient rANS tables\n\n")

        f.write(f"// {RANS_COEF_NTABLES} rANS cumulative frequency tables"
                f" ({RANS_COEF_NTABLES // 4} alpha x 4 activity),\n"
                f"// freq[s] = cf[s + 1] - cf[s]\n")
        f.write(fmt_2d("rans_cf", "uint16_t", cf) + "\n\n")

        f.write("// log2(sigma_pair) in Q8 for alpha bin computation\n")
        f.write(fmt_1d("rans_log2_sigma_q8", "int16_t", sigma_q8, 10) + "\n\n")

        f.write("// Precomputed reciprocals: floor((2^32-1) / freq)\n")
        f.write(fmt_2d("rans_rcp", "uint32_t", rcp) + "\n\n")

        f.write("// Precomputed symbol costs in Q8 fractional bits\n")
        f.write(fmt_2d("rans_cost_q8", "int16_t", cost_q8) + "\n\n")

        f.write("// Exponent rANS tables: [model enum order * 4 + position group]\n")
        f.write("// 13 slots = centered magnitude 0..11 + escape\n")
        f.write(fmt_1d("rans_exp_group", "uint8_t", exp_group, 20) + "\n\n")
        f.write(fmt_1d("rans_exp_center", "int16_t", exp_center, 12) + "\n\n")
        f.write(fmt_2d("rans_exp_cf", "uint16_t", exp_cf) + "\n\n")
        f.write(fmt_2d("rans_exp_rcp", "uint32_t", exp_rcp) + "\n\n")
        f.write(fmt_2d("rans_exp_cost_q8", "int16_t", exp_cost_q8) + "\n")

    print(f"  Wrote {src}")
    cf_bytes = RANS_COEF_NTABLES * (RANS_MAX_SYM + 1) * 2
    print(f"  ROM: cf={cf_bytes}B"
          f" rcp={RANS_COEF_NTABLES*RANS_MAX_SYM*4}B"
          f" cost={RANS_COEF_NTABLES*RANS_MAX_SYM*2}B"
          f" total={cf_bytes + RANS_COEF_NTABLES*RANS_MAX_SYM*(4+2)}B")
    print(f"  Added {len(exp_cf)} exponent tables from {exp_data}")
    print("Done.")


if __name__ == "__main__":
    main()
